### ISSUE TITLE
Release of train et test

### ISSUE THREAD

**Issue by udacityyy** [Leozyc-waseda/Lidar_Openpcdet_ST3D#3]
Hello, first of all, thank you for this, I have tried it on custom dataset and launched demo.py to try it and it worked, i was wondering if you're going to release the train and test.py methods any time soon, I'm very interested, thank you !

**Comment by Leozyc-waseda** [comment]
I've been busy with other things recently so I didn't plan to update the training part.  Maybe Openpcdet officials will also publish how to train their own data sets recently.
