### ISSUE TITLE
Empty .bin file in gt_database

### ISSUE THREAD

**Issue by hieunm1821** [Leozyc-waseda/Lidar_Openpcdet_ST3D#4]
Hi. Thanks for writing the data loader.
However, my output bin in gt_database is empty. Is it an error?

**Comment by Leozyc-waseda** [comment]
Hi.
Looks like yes, I'm not sure where I'm going wrong, since lately I don't need to train on my own data anymore, so I've been missing the test-train part.
Maybe I'll debug it when I'm done with what I'm doing, or you can debug for yourself. 
PR is very welcome.
